### ISSUE TITLE
GLSL panoramas don't render

### ISSUE THREAD

**Issue by steve-the-player** [magistermaks/mod-glsl#10]
Mod loader: Fabric  
Minecraft version: 1.20.1  
Mod version: 0.2.1  
Modloader version: Fabric Loader v0.14.25, Fabric API v1.91.0+1.20.1  
Modpack info: https://www.modrinth.com/modpack/adventurous  
Nothing shows up in the [.log files](https://mclo.gs/wM1D6v0) relating to errors with the mod  

I can't get any glsl panoramas to render, not even the one that's included by default. Not sure why.

**Comment by magistermaks** [comment]
i can't reproduce this, try using the newest version of the mod
