### ISSUE TITLE
README on GitHub is wrong

### ISSUE THREAD

**Issue by sternschnaube** [magistermaks/mod-glsl#11]

**Comment by magistermaks** [comment]
what? in what way?

**Comment by magistermaks** [comment]
ah ok i see, sure i can fix it later

**Comment by venaminecraft** [comment]
Good 😄

**Comment by magistermaks** [comment]
Fixed in [4a1534f](https://github.com/magistermaks/mod-glsl/commit/4a1534f4782bd7b8367bd2757e75704fc2454c41) :slightly_smiling_face:

**Comment by venaminecraft** [comment]
I was just meaning GitHub 😃

![image](https://github.com/magistermaks/mod-glsl/assets/120551916/802c08fd-8c29-48eb-89e7-72a1bb6ed1e4)

**Comment by magistermaks** [comment]
well yes, and i fixed it in [4a1534f](https://github.com/magistermaks/mod-glsl/commit/4a1534f4782bd7b8367bd2757e75704fc2454c41) :+1:
